const DEPT_LIST = [
  { id:"police", name:"Police Commissioner", color:"#3b5a80", soft:"#e7edf5", stat:"crime", dir:-1, icon:"<path d=\"M12 2 L20 5 V11 C20 16 16.5 20 12 22 C7.5 20 4 16 4 11 V5 Z\"/>",
    resources:[{key:"officers",label:"Officers",start:10}],
    tiers:["Digitized FIR", "Forensics Lab", "CCTV Network", "Predictive Policing", "Smart City Policing"],
    actions:[["Patrol","1 AP","Crime −2 in one district"], ["Investigate","2 AP","Reveal one Hidden token, anywhere"], ["Raid","3 AP","Remove a Crime Syndicate token, Crime −5"], ["Hire Officers","2 AP","+3 Officers (₹15 GC)"], ["Anti-Corruption Campaign","4 AP","Corruption −5, Reputation +10"]] },
  { id:"health", name:"Health Minister", color:"#c65b52", soft:"#f8e6e4", stat:"health", dir:1, icon:"<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M12 8v8M8 12h8\"/>",
    resources:[{key:"doctors",label:"Doctors",start:6}, {key:"beds",label:"Bed Capacity",start:8}],
    tiers:["District Hospital", "Medical College", "Subsidized Medicine", "AI Diagnostics", "Universal Healthcare"],
    actions:[["Treat Patients","1 AP","Clear up to 3 Sick cubes"], ["Vaccination Drive","2 AP","Prevents the next Health-related Crisis card"], ["Hire Doctors","2 AP","+2 Doctors"], ["Build Clinic","3 AP","+3 Capacity, permanently"]] },
  { id:"education", name:"Education Minister", color:"#4f7fae", soft:"#e8f0f8", stat:"education", dir:1, icon:"<path d=\"M4 6 C7 4 10 4 12 6 C14 4 17 4 20 6 V19 C17 17 14 17 12 19 C10 17 7 17 4 19 Z\"/>",
    resources:[{key:"schools",label:"Schools",start:5}],
    tiers:["Smart Classrooms", "Teacher Certification", "Scholarship Fund", "Research University", "Free Higher Education"],
    actions:[["Run Classes","1 AP","Education +2"], ["Teacher Training","2 AP","Locks in this round\\'s Education gains"], ["Scholarship Program","3 AP","Move 1 cube Unemployed → Student"], ["Build School","3 AP","+1 School, raises the Education cap"]] },
  { id:"transport", name:"Transport Minister", color:"#c07a3f", soft:"#f6e9dc", stat:"infrastructure", dir:1, icon:"<path d=\"M5 19 L9 4 H15 L19 19\"/><path d=\"M6.5 14h11\"/>",
    resources:[{key:"rail",label:"Rail Lines",start:3}],
    tiers:["Highway Expansion", "Metro System", "EV Incentives", "Smart Traffic AI", "National Rail Grid"],
    actions:[["Pothole Repair","1 AP","Infrastructure +2"], ["Traffic Management","2 AP","Crime −2"], ["Expand Rail","3 AP","+1 Rail Line, Employment +3"], ["Fuel Subsidy","2 AP","Inflation −1, this round only"]] },
  { id:"municipal", name:"Municipal Commissioner", color:"#3f9a72", soft:"#e5f4ec", stat:"pollution", dir:-1, icon:"<path d=\"M5 21V10l7-5 7 5v11\"/><path d=\"M9 21v-6h6v6\"/>",
    resources:[{key:"wasteCap",label:"Waste Capacity",start:10}],
    tiers:["Drainage Overhaul", "Recycling Program", "Smart Water Grid", "Green Belt Initiative", "Zero Waste City"],
    actions:[["Waste Collection","1 AP","Pollution −2"], ["Water Treatment","2 AP","Prevents Health overflow from water-related Crisis cards"], ["Park Development","2 AP","Trust +3"], ["Construction Crackdown","3 AP","Corruption −3, Crime −2"]] },
  { id:"food", name:"Food Commissioner", color:"#8aa851", soft:"#eef3e1", stat:"foodSafety", dir:1, icon:"<path d=\"M12 21V9\"/><path d=\"M12 9c-2 0-3.2-1.6-3.2-4C10.8 5 12 6.2 12 9z\"/><path d=\"M12 9c2 0 3.2-1.6 3.2-4C13.2 5 12 6.2 12 9z\"/>",
    resources:[{key:"stalls",label:"Market Stalls",start:6}],
    tiers:["Quality Certification", "Farmer Cooperatives", "Supply Chain Digitization", "Public Distribution Network", "National Food Security"],
    actions:[["Market Inspection","1 AP","Food Safety +5"], ["Subsidize Staples","2 AP","Trust +2, Inflation −1"], ["Farmer Support","2 AP","Prevents the next Farmer Protest Crisis card"], ["Cold Storage","3 AP","Food Safety stops decaying round to round"]] },
  { id:"finance", name:"Finance Minister", color:"#c9a13a", soft:"#f7f0dc", stat:"treasury", dir:1, icon:"<path d=\"M4 10 L12 4 L20 10 M5 10V19M9 10V19M15 10V19M19 10V19M3 19H21\"/>",
    resources:[{key:"taxRate",label:"Tax Rate %",start:6}],
    tiers:["GST Reform", "Digital Banking", "Foreign Investment", "Inflation Controls", "Sovereign Wealth Fund"],
    actions:[["Adjust Tax Rate","1 AP","Change the rate ±2%"], ["Audit","2 AP","Reveal a department\\'s Personal Wealth (the number only)"], ["Stimulus Package","3 AP","Employment +5, Treasury −30 GC"], ["Debt Repayment","2 AP","National Debt −20 GC"]] },
  { id:"media", name:"Media Head", color:"#8a63ad", soft:"#f0e8f6", stat:"trust", dir:1, icon:"<path d=\"M3 10v4h3l7 4V6l-7 4H3z\"/><path d=\"M14.5 8.5c1.3 1.2 1.3 5.8 0 7\"/>",
    resources:[{key:"credits",label:"Story Credits",start:4}],
    tiers:["Investigative Desk", "Digital Platform", "Fact-Check Bureau", "National Broadcaster", "State Media Control"],
    actions:[["Expose","1 Credit","Force one Hidden token to flip, anywhere"], ["Cover Story","1 Cr + ₹10 GC","Enables another department\\'s covert move"], ["Propaganda Push","2 Credits","Trust +5, hidden Corruption +2 (doesn\\'t show yet)"], ["Panic Headline","2 Credits","Target Reputation −10, yours −5"]] },
  { id:"judiciary", name:"Judiciary", color:"#6b7280", soft:"#eceef1", stat:"crime", dir:-1, icon:"<path d=\"M12 3v18M5 7h14M5 7L2.5 13h5L5 7zM19 7l-2.5 6h5L19 7z\"/>",
    resources:[{key:"judges",label:"Judges",start:4}, {key:"courtSlots",label:"Court Slots",start:6}],
    tiers:["Case Digitization", "Fast Courts", "Judicial Independence", "Legal Aid Network", "Supreme Oversight"],
    actions:[["Hear Case","1 AP","Clear 2 backlogged cases, Crime −1"], ["Fast-Track Ruling","2 AP","Clear 4 cases, Trust −2"], ["Appoint Judges","2 AP","+2 Judges"], ["Anti-Corr. Tribunal","4 AP","Force-reveal every Hidden Corruption token at the table"]] },
  { id:"pm", name:"Prime Minister", color:"#c9973a", soft:"#f7edd9", stat:null, dir:0, icon:"<path d=\"M12 2l2.6 6.6L22 9l-5.4 4.6L18 22l-6-4-6 4 1.4-8.4L2 9l7.4-.4L12 2z\"/>",
    resources:[],
    tiers:[],
    actions:[["Allocate Funding","2 AP","Move ₹15 GC from Treasury to any one department"], ["Declare Emergency","3 AP","Every department +2 AP this round; Trust −5"], ["Privatize Sector","4 AP","Double one department\\'s output for 3 rounds"], ["Snap Election","5 AP","Force an Election Check immediately, off-schedule"]] },
];

const TIER_COSTS = ["3 AP + ₹20 Treasury", "3 AP + ₹30 Treasury", "4 AP + ₹40 Treasury", "4 AP + ₹50 Treasury", "5 AP + ₹60 Treasury"];

const CRISIS_CARDS = [
  ["Monsoon Floods", "Seasonal flooding overwhelms low-lying districts.", "Infrastructure −8, Health −4, every department −1 AP this round.", ["transport", "health"]],
  ["Farmer Protest", "Farmers block highways over grain pricing.", "Crime +4, Trust −4 — unless Food Commissioner spends 3 AP to negotiate.", ["food", "police"]],
  ["Fake Medicine Scandal", "Counterfeit drugs found circulating in public hospitals.", "Health −6, unless Health Minister reveals a Hidden Corruption token.", ["health"]],
  ["Power Shortage", "Grid failures hit three states simultaneously.", "Employment −4, Pollution +4.", ["municipal", "finance"]],
  ["Cyber Attack", "A ransomware attack hits a government payment system.", "Treasury −18 GC, unless CCTV Network is owned.", ["finance", "police"]],
  ["Heatwave", "Record temperatures strain hospitals and the grid.", "Health −5. Move 3 cubes Working → Sick.", ["health"]],
  ["Festival Rush", "A major festival lifts spending and street commerce.", "Employment +4, Crime +3, Trust +2.", ["finance", "police", "media"]],
  ["Air Pollution Emergency", "Smog forces school closures in the capital.", "Health −8, Education −4.", ["health", "education", "municipal"]],
  ["Rail Accident", "A signal failure causes a major derailment.", "Infrastructure −6, Trust −6.", ["transport", "media"]],
  ["Fuel Crisis", "Global oil prices spike overnight.", "Inflation +2, Employment −4.", ["finance"]],
  ["Water Contamination", "A district reports contaminated municipal water.", "Move 4 cubes Working → Sick. Health −3.", ["municipal", "health"]],
  ["Tech Startup Boom", "A wave of new tech firms open regional offices.", "Treasury +25 GC, Inflation +1.", ["finance"]],
  ["Judicial Backlog Exposed", "Media reports expose years-long case delays.", "Crime +6, Trust −5.", ["judiciary", "media"]],
  ["Foreign Aid Offer", "A foreign government offers unconditional development aid.", "Treasury +25 GC. No strings.", ["finance"]],
  ["Viral Misinformation", "A fabricated story about the government spreads rapidly.", "Trust −8.", ["media"]],
  ["Grassroots Success Story", "A district-level reform effort goes viral for the right reasons.", "Trust +5, Corruption −3.", ["media"]],
  ["Vaccine Shortage", "Health under 50 and Treasury under 50.", "Health −8, Trust −5, unless a Vaccination Drive is active.", ["health", "media"]],
  ["Teacher Strike", "Education Reputation under 30.", "Education −6, Employment −2.", ["education", "finance"]],
  ["Bridge Collapse", "Infrastructure under 35.", "Infrastructure −15, move 2 cubes to Sick, Trust −10.", ["transport", "media"]],
  ["Election Fraud Allegation", "Corruption over 60, during an election round.", "Approval result −10 flat.", ["media", "pm"]],
  ["Currency Devaluation", "Inflation over 12%.", "Treasury −10%, Employment −5.", ["finance"]],
  ["Slum Fire", "Pollution over 60 and Infrastructure under 40.", "Move 3 cubes Working → Sick. Municipal Reputation −10.", ["municipal"]],
  ["Coalition Collapse", "Approval under 40 outside an election round.", "Trigger an immediate off-schedule Election Check.", ["pm"]],
  ["Heatwave Blackout", "Infrastructure under 45 and Pollution over 55.", "Health −6, Employment −3.", ["health", "finance"]],
  ["Grain Export Ban", "Inflation over 10%.", "Food Safety −10, Treasury +15 GC.", ["food", "finance"]],
  ["Metro Construction Scandal", "Transport Reputation under 30.", "Transport gains halved for 2 rounds, Corruption +4.", ["transport"]],
  ["Doctor Emigration Wave", "Health Reputation under 25.", "Lose 2 Doctors permanently, Health −5.", ["health"]],
  ["Religious Festival Clash", "Crime over 45 and Trust under 50.", "Move 2 cubes Working → Sick. Police must Patrol for free.", ["police"]],
  ["Startup Tax Evasion Exposed", "Finance Reputation under 30.", "Treasury −20 GC, Corruption +5.", ["finance"]],
  ["School Building Collapse", "Education Tier ≤1 and Infrastructure under 40.", "Remove 1 cube, Education −10, Trust −10.", ["education", "media"]],
  ["Cyclone Landfall", "Scheduled — draw every 4th round.", "Infrastructure −10, Health −5, all −1 AP; Municipal may spend 2 AP to halve.", ["transport", "health", "municipal"]],
  ["Anti-Corruption Rally", "Corruption over 55.", "Trust +5. Every player reveals one Hidden token of their choice.", ["media", "judiciary"]],
  ["Black Market Medicine Bust", "A Police Raid succeeded this game and Health under 60.", "Health +5, Police Reputation +8.", ["health", "police"]],
  ["Farmer Debt Crisis", "Farmer Support unused for 3+ rounds.", "Employment −5, Crime +3.", ["food", "finance", "police"]],
  ["Judicial Reform Bill", "PM spent any AP this round.", "Judiciary gains +1 free Court Slot permanently, Trust +3.", ["judiciary", "pm"]],
  ["Global Recession", "Rare random draw.", "Treasury −15%, Employment −8, Inflation +3.", ["finance"]],
  ["Whistleblower", "Any Hidden token exists at the table.", "A free Investigate action is granted to a player of the drawer\\'s choice.", ["police", "media"]],
  ["Festival Stampede", "Crime over 50 and Infrastructure under 50.", "Trust −8. Remove 1 population cube permanently.", ["media", "police"]],
  ["Border Skirmish", "Random draw.", "All departments −1 AP, PM gains +2 AP.", ["pm"]],
  ["Judicial Reform Push", "Corruption falling for 2 rounds straight.", "Judiciary Reputation +10, Crime −3.", ["judiciary", "police"]],
];

const BRIBE_CARDS = [
  ["Police", "Precinct Expansion", "A contractor offers ₹15 GC to ignore an illegal precinct expansion.", "If accepted: +15 GC personal wealth, Corruption +3, becomes a Hidden token.", "If declined: Public Reputation +5."],
  ["Police", "Protection Racket", "A gang offers ₹18 GC/round for reduced Patrol in their district.", "If accepted: +18 GC this round, Crime +3/round it continues, Corruption +2/round.", "If declined: nothing changes."],
  ["Police", "Evidence Disposal", "An anonymous offer of ₹14 GC to lose evidence in a minor case.", "If accepted: +14 GC, Corruption +4, becomes a Hidden token.", "If declined: nothing gained."],
  ["Health", "Doctor Diversion", "A private hospital chain offers ₹18 GC to divert Doctors to their wards for 2 rounds.", "If accepted: +18 GC, department Capacity −2 for 2 rounds, Corruption +3.", "If declined: Public Reputation +5."],
  ["Health", "Trial Shortcuts", "A pharma company offers ₹20 GC to skip a safety review stage.", "If accepted: +20 GC, Corruption +5, raises odds of a Health-linked Crisis next draw.", "If declined: nothing gained."],
  ["Health", "Equipment Kickback", "A supplier offers ₹12 GC for a no-bid equipment contract.", "If accepted: +12 GC, Corruption +3, becomes a Hidden token.", "If declined: Public Reputation +4."],
  ["Education", "Textbook Contract", "A publisher offers ₹12 GC for an exclusive, overpriced textbook contract.", "If accepted: +12 GC, Education −3, Corruption +2.", "If declined: nothing gained."],
  ["Education", "Exam Paper Leak", "A tutoring network offers ₹14 GC to leak an exam in advance.", "If accepted: +14 GC, Education −5 next round, Corruption +3.", "If declined: nothing gained."],
  ["Education", "Fake Degree Mill", "A private college offers ₹17 GC to quietly accredit a diploma mill.", "If accepted: +17 GC, Corruption +4, becomes a Hidden token.", "If declined: Public Reputation +5."],
  ["Transport", "Substandard Materials", "A contractor offers ₹20 GC to approve cheap road materials.", "If accepted: +20 GC, next 2 Infrastructure gains halved, Corruption +4.", "If declined: Public Reputation +8."],
  ["Transport", "Toll Booth Skimming", "A toll operator offers ₹13 GC/round to underreport revenue.", "If accepted: +13 GC this round (repeatable), Treasury −13 GC/round it continues, Corruption +3/round.", "If declined: nothing changes."],
  ["Transport", "License Fast-Track", "A transport company offers ₹9 GC to skip vehicle safety inspections.", "If accepted: +9 GC, Corruption +2, becomes a Hidden token.", "If declined: nothing gained."],
  ["Municipal", "Flood Zone High-Rise", "A builder offers ₹14 GC to overlook an illegal high-rise in a flood zone.", "If accepted: +14 GC, Infrastructure −4 on the next flood-type Crisis, Corruption +3.", "If declined: nothing gained."],
  ["Municipal", "Land Zoning Change", "A developer offers ₹19 GC to rezone protected land.", "If accepted: +19 GC, Pollution +6 permanent, Corruption +4.", "If declined: Public Reputation +6."],
  ["Municipal", "Garbage Contract Kickback", "A waste-management firm offers ₹11 GC for an inflated collection contract.", "If accepted: +11 GC, Corruption +2, becomes a Hidden token.", "If declined: nothing gained."],
  ["Food", "Expired Stock", "A distributor offers ₹10 GC to pass expired stock as fresh.", "If accepted: +10 GC, Food Safety −15, Corruption +3.", "If declined: nothing gained."],
  ["Food", "Import Quota Favor", "An importer offers ₹17 GC for a favorable quota allocation.", "If accepted: +17 GC, Inflation +1, Corruption +3.", "If declined: Public Reputation +5."],
  ["Food", "Subsidy Diversion", "An official offers ₹15 GC to redirect staple subsidies to a private buyer.", "If accepted: +15 GC, Treasury −8 GC, Corruption +3, becomes a Hidden token.", "If declined: nothing gained."],
  ["Finance", "Tax Exemption", "A corporation offers ₹25 GC for a quiet tax exemption.", "If accepted: +25 GC, Treasury −15 GC this round, Corruption +4.", "If declined: Public Reputation +6."],
  ["Finance", "Audit Suppression", "Another player offers ₹12 GC to bury a negative Audit result about them.", "If accepted: +12 GC, that Audit result can never be revealed this game, Corruption +3.", "If declined: nothing gained."],
  ["Finance", "Loan Approval Favor", "A businessman offers ₹15 GC to approve a loan against policy.", "If accepted: +15 GC, National Debt +10 GC, Corruption +3, becomes a Hidden token.", "If declined: nothing gained."],
  ["Media", "Buried Story", "A politician offers ₹15 GC to kill a scandal story about themselves.", "If accepted: +15 GC, that department\\'s next Hidden token is protected from Expose for 2 rounds, Corruption +3.", "If declined: the story runs — target Reputation −10, yours +5."],
  ["Media", "Leak for Hire", "A rival offers ₹20 GC to leak a competitor\\'s Hidden token early.", "If accepted: +20 GC, immediately flip one named token of your choice, Corruption +2.", "If declined: nothing happens."],
  ["Media", "Sponsored Segment", "A corporation offers ₹12 GC for favorable coverage disguised as news.", "If accepted: +12 GC, Trust +3, becomes a Hidden token.", "If declined: nothing gained."],
  ["Judiciary", "Delay Motion", "A family offers ₹16 GC to delay a case indefinitely.", "If accepted: +16 GC, permanent case backlog (+1 Crime/round it sits), Corruption +5.", "If declined: nothing gained."],
  ["Judiciary", "Evidence Tampering", "An anonymous offer of ₹22 GC to permanently destroy one Hidden token.", "If accepted: +22 GC, destroys one Hidden token of your choice forever, Corruption +7.", "If declined: nothing gained."],
  ["Judiciary", "Lenient Sentencing", "A corporation offers ₹18 GC for a favorable ruling in a business dispute.", "If accepted: +18 GC, Treasury −10 GC, Corruption +4, becomes a Hidden token.", "If declined: Public Reputation +6."],
];